Changes to configure.in don't do much good unless I run autoconf and commit the new configure script as well.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2104,7 +2104,7 @@ else
 
 int main ()
 {
-  char test[10];
+  char test[11];
   unsigned long long int num = 0xdeadbeef;
   sprintf (test, NIX, num);
   if (strcmp (test, "3735928559") == 0)
@@ -2130,6 +2130,43 @@ rm -fr conftest*
 fi
 
 
+
+for ac_prog in 'bison -y' byacc
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:2140: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_YACC'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$YACC"; then
+  ac_cv_prog_YACC="$YACC" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_YACC="$ac_prog"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+YACC="$ac_cv_prog_YACC"
+if test -n "$YACC"; then
+  echo "$ac_t""$YACC" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+test -n "$YACC" && break
+done
+test -n "$YACC" || YACC="yacc"
+
+test "$YACC" = "yacc" && { echo "configure: error: "need bison or byacc"" 1>&2; exit 1; }
 
 if [ -f /lib/libc-2* ]; then
  V_DEFINES="$V_DEFINES -D_BSD_SOURCE"
@@ -2303,6 +2340,7 @@ s%@SHLICC2@%$SHLICC2%g
 s%@CC@%$CC%g
 s%@SET_MAKE@%$SET_MAKE%g
 s%@U_LONG_LONG_TYPE@%$U_LONG_LONG_TYPE%g
+s%@YACC@%$YACC%g
 s%@V_CCOPT@%$V_CCOPT%g
 s%@V_INCLS@%$V_INCLS%g
 s%@V_DEFINES@%$V_DEFINES%g
